# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mann_kendall_S <- function(x) {
    .Call('_tjdc_mann_kendall_S', PACKAGE = 'tjdc', x)
}

mann_kendall_S_and_slope <- function(x, time) {
    .Call('_tjdc_mann_kendall_S_and_slope', PACKAGE = 'tjdc', x, time)
}

c_contextual_mann_kendall <- function(x, nrow, time, neighbourhood = 2L, calc_slope = FALSE) {
    .Call('_tjdc_c_contextual_mann_kendall', PACKAGE = 'tjdc', x, nrow, time, neighbourhood, calc_slope)
}

c_mann_kendall_test <- function(x) {
    .Call('_tjdc_c_mann_kendall_test', PACKAGE = 'tjdc', x)
}

c_mann_kendall_test_and_beta <- function(x, t) {
    .Call('_tjdc_c_mann_kendall_test_and_beta', PACKAGE = 'tjdc', x, t)
}

neighbour_cells_queen_row_col <- function(i, nrow, ncol) {
    .Call('_tjdc_neighbour_cells_queen_row_col', PACKAGE = 'tjdc', i, nrow, ncol)
}

neighbour_cells_queen_col_row <- function(i, nrow, ncol) {
    .Call('_tjdc_neighbour_cells_queen_col_row', PACKAGE = 'tjdc', i, nrow, ncol)
}

forward_neighbour_cells_queen_row_col <- function(i, nrow, ncol) {
    .Call('_tjdc_forward_neighbour_cells_queen_row_col', PACKAGE = 'tjdc', i, nrow, ncol)
}

forward_neighbour_cells_queen_col_row <- function(i, nrow, ncol) {
    .Call('_tjdc_forward_neighbour_cells_queen_col_row', PACKAGE = 'tjdc', i, nrow, ncol)
}

neighbour_cells_rook_row_col <- function(i, nrow, ncol) {
    .Call('_tjdc_neighbour_cells_rook_row_col', PACKAGE = 'tjdc', i, nrow, ncol)
}

neighbour_cells_rook_col_row <- function(i, nrow, ncol) {
    .Call('_tjdc_neighbour_cells_rook_col_row', PACKAGE = 'tjdc', i, nrow, ncol)
}

forward_neighbour_cells_rook_row_col <- function(i, nrow, ncol) {
    .Call('_tjdc_forward_neighbour_cells_rook_row_col', PACKAGE = 'tjdc', i, nrow, ncol)
}

forward_neighbour_cells_rook_col_row <- function(i, nrow, ncol) {
    .Call('_tjdc_forward_neighbour_cells_rook_col_row', PACKAGE = 'tjdc', i, nrow, ncol)
}

